---
grails:
    profile: web
    codegen:
        defaultPackage: puzzlehunt
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

    plugin:
        cookiesession:
            enabled: true
            encryptcookie: true
            cryptoalgorithm: "Blowfish"
            sessiontimeout: 3600
            cookiename: 'puzzlesession'
            sethttponly: true
            springsecuritycompatibility: false
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

puzzlehunt:
    puzzleTimeout: 2000
    resourcePath: bootstrap

environments:
    development:
        puzzlehunt:
            bootstrapPath: bootstrap
        dataSource:
            dbCreate: create-drop
            driverClassName: org.apache.derby.jdbc.ClientDriver
            url: jdbc:derby://localhost:1527/PUZZLEHUNT;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: apple
            password: cherry
        grails:
            plugin:
                cookiesession:
                    setsecure: false
                    secret: 'dev'
    test:
        puzzlehunt:
            bootstrapPath: bootstrap
        dataSource:
            dbCreate: update
            driverClassName: org.apache.derby.jdbc.ClientDriver
            url: jdbc:derby://localhost:1527/PUZZLEHUNT;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            username: apple
            password: cherry
        grails:
            plugin:
                cookiesession:
                    setsecure: false
                    secret: 'test'
    production:
        dataSource:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            driverClassName: com.mysql.jdbc.Driver
            dbCreate: none
            properties:
                reconnect: true
        grails:
            plugin:
                cookiesession:
                    setsecure: true
                    #secret: pass as arg
